name: BungeePlayerCounter
author: Alphart
version: 1.1.2
main: fr.Alphart.BungeePlayerCounter.BPC
permissions:
    bungeeplayercounter.display:
        description: Display the scoreboard
        default: op