name: BungeePlayerCounter
author: Alphart
version: ${project.version}
main: fr.Alphart.BungeePlayerCounter.BPC
permissions:
    bungeeplayercounter.display:
        description: Display the scoreboard
        default: true
    bungeeplayercounter.toggle:
        description: Toggle the scoreboard
        default: true
    bungeeplayercounter.reload:
        description: Reload the plugin
        default: op
commands:
  bpc:
    description: Main command of the plug !
    usage: /<command>   